# Generated by Django 4.2.24 on 2025-09-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_artisan_payment_artisan_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='artisan_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='held_by_platform',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='released_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_code',
        ),
        migrations.AddField(
            model_name='payment',
            name='artisan_phone',
            field=models.CharField(default='UNKNOWN', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='buyer_phone',
            field=models.CharField(default='UNKNOWN', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('held', 'Held'), ('released', 'Released'), ('refunded', 'Refunded')], default='held', max_length=10),
        ),
    ]
