# Generated by Django 5.2.6 on 2025-09-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='artisan_image_url',
            new_name='image_url',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('artisan', 'Artisan'), ('buyer', 'Buyer')], default='buyer', max_length=10),
        ),
    ]
