# Generated by Django 4.2 on 2025-09-17 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AlterField(
            model_name='portfolioimage',
            name='image',
            field=models.ImageField(default=None, upload_to='portfolio_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'National ID must be 8 digits.')]),
        ),
    ]
