# Generated by Django 5.2.6 on 2025-09-19 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artisanprofile",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"user_type": "ARTISAN"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
