# Generated by Django 4.2 on 2025-09-18 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_latitude_remove_user_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'ARTISAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='artisanprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
