# Generated by Django 4.2 on 2025-09-18 12:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_username_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artisanportfolio",
            name="artisan",
            field=models.ForeignKey(
                limit_choices_to={"user_type": "ARTISAN"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{8}$", "National ID must be 8 digits."
                    )
                ],
            ),
        ),
    ]
