# Generated by Django 4.2 on 2025-09-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_artisanportfolio_artisan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="user",
            name="longitude",
        ),
    ]
