# Generated by Django 4.2 on 2025-09-19 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_artisanprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, related_name='artisanprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
