# Generated by Django 5.2.6 on 2025-09-16 06:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "National ID must be 8 digits."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("ARTISAN", "Artisan"), ("BUYER", "Buyer")],
                default="BUYER",
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "Phone number must be exactly 10 digits."
                    )
                ],
            ),
        ),
    ]
