# Generated by Django 5.2.4 on 2025-09-17 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_national_id_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{10}$", "Phone number must be exactly 10 digits."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("ARTISAN", "Artisan"), ("BUYER", "Buyer")],
                default="BUYER",
                max_length=10,
            ),
        ),
    ]
