# Generated by Django 5.2.6 on 2025-09-19 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_shoppingcart_user"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="inventory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.inventory",
            ),
        ),
    ]
