# Generated by Django 5.2.6 on 2025-09-15 05:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_added_at_shoppingcart_created_at_and_more'),
        ('products', '0004_alter_inventory_category'),
        ('users', '0003_alter_user_national_id_artisanportfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='total_items',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.inventory'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Quantity must be positive')]),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='users.user'),
        ),
    ]
