# Generated by Django 5.2.6 on 2025-09-15 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_shoppingcart_user'),
        ('users', '0003_alter_user_national_id_artisanportfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='users.user'),
        ),
    ]
