# Generated by Django 5.2.6 on 2025-09-15 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_shoppingcart_user'),
        ('users', '0003_alter_user_national_id_artisanportfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='total_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
