# Generated by Django 5.2.6 on 2025-09-15 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_shoppingcart_user'),
        ('products', '0004_alter_inventory_category'),
        ('users', '0003_alter_user_national_id_artisanportfolio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Shopping Cart', 'verbose_name_plural': 'Shopping Carts'},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='total_items',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='custom_options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.OneToOneField(limit_choices_to={'user_type': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to='users.user'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'inventory'), name='unique_cart_inventory'),
        ),
    ]
