# Generated by Django 5.2.6 on 2025-09-17 15:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('reference_images', models.URLField(blank=True, null=True)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('material-sourcing', 'Material-sourcing'), ('in-progress', 'In-progress'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='material_sourced', max_length=50)),
                ('quote_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('material_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labour_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('artisan_id', models.ForeignKey(limit_choices_to={'user_type': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, related_name='custom_requests_as_artisan', to='users.user')),
                ('buyer_id', models.ForeignKey(limit_choices_to={'user_type': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='custom_requests_as_buyer', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('ready-made', 'Ready-made'), ('custom', 'Custom')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rejection_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_confirmed', models.BooleanField(default=False)),
                ('rejection_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan_id', models.ForeignKey(limit_choices_to={'user_type': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_artisan', to='users.user')),
                ('buyer_id', models.ForeignKey(limit_choices_to={'user_type': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='orders_buyer', to='users.user')),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In-progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('artisan_upload', models.URLField(blank=True, null=True)),
                ('buyer_approval', models.BooleanField(default=False)),
                ('approval_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artisan_id', models.ForeignKey(limit_choices_to={'user_type': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_id', models.ForeignKey(limit_choices_to={'user_type': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to='users.user')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
    ]
