# Generated by Django 5.2.6 on 2025-09-19 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="artisan",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "artisan"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_as_artisan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"user_type": "buyer"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_as_buyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
