# Generated by Django 5.2.6 on 2025-09-19 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_artisan_alter_order_buyer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="artisan",
        ),
        migrations.RemoveField(
            model_name="order",
            name="buyer",
        ),
    ]
