# Generated by Django 5.2.6 on 2025-10-01 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_product"),
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customdesignrequest",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.inventory",
            ),
        ),
        migrations.AddField(
            model_name="orderstatus",
            name="request",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.customdesignrequest",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customdesignrequest",
            name="reference_images",
            field=models.ImageField(default=None, upload_to="reference_images/"),
        ),
        migrations.AlterField(
            model_name="customdesignrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("material-sourcing", "Material-sourcing"),
                    ("in-progress", "In-progress"),
                    ("completed", "Completed"),
                ],
                default="material_sourcing",
                max_length=50,
            ),
        ),
    ]
