# Generated by Django 5.2.6 on 2025-10-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_customdesignrequest_product_orderstatus_request_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderstatus",
            name="image",
        ),
        migrations.AddField(
            model_name="customdesignrequest",
            name="artisan_uploads",
            field=models.ImageField(default=None, upload_to="order_images/"),
        ),
    ]
