# Generated by Django 5.2.6 on 2025-09-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('pottery', 'Pottery'), ('tailoring', 'Tailoring'), ('basketry', 'Basketry'), ('weaving', 'Weaving'), ('crocheting', 'Crocheting'), ('ceramics', 'Ceramics')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.IntegerField()),
                ('image_url', models.URLField()),
                ('is_customizable', models.BooleanField(default=False)),
                ('custom_options', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artisan_id', models.ForeignKey(limit_choices_to={'user_type': 'artisan'}, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
