# Generated by Django 5.2.6 on 2025-09-12 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='artisan',
            new_name='artisan_id',
        ),
    ]
