# Generated by Django 5.2.6 on 2025-09-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_artisan_inventory_artisan_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('pottery', 'Pottery'), ('tailoring', 'Tailoring'), ('basketry', 'Basketry'), ('weaving', 'Weaving'), ('crocheting', 'Crocheting'), ('ceramics', 'Ceramics')], max_length=50),
        ),
    ]
