# Generated by Django 5.2.6 on 2025-09-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_inventory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='category',
            field=models.CharField(choices=[('pottery', 'Pottery'), ('tailoring', 'Tailoring'), ('basketry', 'Basketry'), ('weaving', 'Weaving'), ('crocheting', 'Crocheting'), ('ceramics', 'Ceramics'), ('jewelry', 'jewerly')], max_length=50),
        ),
    ]
